### PR TITLE
fix: display ```coming soon``` message on profile picture upload butt…

### LINKED ISSUE #525: Profile picture upload is not implemented
It would be good to either remove or replace the button functionality with a popup telling `Coming soon!`

### PR DESCRIPTION
**Pull request by hlavkat**
…on click

resolved #525

### CODE REVIEW

File: src/lib/components/edit-client.svelte [hunk 1]
```diff
@@ -180,7 +181,12 @@
 			/>
 			<section class="profile-helper">
 				<Typography variant="small">{$_('profileImageHelper')}</Typography>
-				<Button variant="solid" dimension="small"><Image size={16} />{$_('uploadImage')}</Button>
+				<Button
+					variant="solid"
+					dimension="small"
+					onclick={() => notImplemented(undefined, 'Coming soon!')}
```
Comment (agazso) [inline src/lib/components/edit-client.svelte]: Please use localised text:
```suggestion
					onclick={() => notImplemented(undefined, $_('Coming soon!'))}
```

**Review by agazso — APPROVED** [review]
