### PR TITLE
fix: newsletter subscription

### LINKED ISSUE #946: Subscribe to newsletter may fail
During signup or from the settings and since it is only reported on the console as error it is silently ignored.

### PR DESCRIPTION
**Pull request by agazso**
Fixes #946 

There is an improvement in error handling with `jsonError` to resemble more both the `json` function call and the `Error` constructor semantically. This allows richer data reporting when an error happens helping debugging issues.

### CODE REVIEW

File: src/routes/account/+page.svelte [hunk 1]
```diff
@@ -141,7 +141,9 @@
 				await manageNewsletterSubscription(false)
 			}
 		} catch (e) {
-			console.error(`Error while ${newsletter_consent ? '' : 'un'}subscribing the newsletter`, e)
+			console.error(`Error while ${newsletter_consent ? '' : 'un'}subscribing the newsletter`, {
```
Comment (vojtechsimetka) [inline src/routes/account/+page.svelte:144]: Should we also display the error?

**Review by vojtechsimetka — APPROVED** [review]

File: src/routes/account/+page.svelte (hunk 1 above)
Comment (agazso) [reply src/routes/account/+page.svelte:144]: Here `e` contains the error and also the cause, that is returned from the backend call.
