### PR TITLE
fix: mobile version

### LINKED ISSUE #562: Layout adjustments on portfolio page
- the investment cards are now inside a container
- I have adjusted the size of the investment cards container from 360 to 380px (to accommodate for the scroll bar)
- horizontal spacing between the cards container and the graphs containers is 8px
- vertical spacing between the graphs container is 8px

**Vertical resizing**

- the cards container can be resized vertically until the size of all graphs, after that content inside (the cards) is scrollable

Image

- by default the each graph container height is 1/3 of the available space
- minimum height is 200px (after that we scroll, see below)

Image

Image

**Scrolling**

Once the graphs are displayed at there minimum size, if the viewport is further reduced vertically (less than 800px currently) then the graphs container are not fully visible and the user needs to scroll down.

- the top (dark) header is fixed and the rest of the secondary header + graphs scrolls under
- the cards container (left sidebar) automatically adjust its size to fit the available space (and its content scrolls inside the container)

Image

Image

### LINKED ISSUE #564: Remove "focus" icon on investment card
Image

I would like to remove the extra "focus" icon displayed after an investment has been focused. To remove focus people should simply click on other cards to make them visible or go from the menu and select "Remove focus" to make all other cards visible

### LINKED ISSUE #565: New graph fullscreen view
- new header design, including the ability to change data visualisation (select Value, Transactions or Breakdown without exiting fullscreen mode)
- new icons for sidebar opening and exiting fullscreen mode
- new investment sidebar to march the new design for investment cards (see https://github.com/snaha/kalkul/issues/562 )
- investment cards sidebar should be closed by default

Image

Image

See here in figma https://www.figma.com/design/CH1QlTIGJk5xblFsNLi3Kn/Kalkul_05?node-id=8167-11659&t=KsvsW2MQv7XaiGQK-1

This also affect the "View only" version which needs to have a mobile version see here in Figma (scroll down for mobile design)
https://www.figma.com/design/CH1QlTIGJk5xblFsNLi3Kn/Kalkul_05?node-id=4395-5747&t=KsvsW2MQv7XaiGQK-1

Image

### LINKED ISSUE #704: Better mobile support

### LINKED ISSUE #873: Mobile version of portfolio view has two show inflation toggles
Related to #565

Image

### LINKED ISSUE #960: Use regular header for most logged-in pages
We should use the default, compact logged-in header on most pages. It's more consistent and also allow people to access help, their account while taking less vertical space.

We just have to add a X button close to the page title.

Image

Affected pages:

- Add client
- Edit client
- Add portfolio
- Edit portfolio
- Add investment
- Edit investment
- Settings/Change email address
- Settings/Change password

### LINKED ISSUE #973: Close button doesn't work on Terms and Privacy pages
The X button in the top-right corner doesn't close the page

### PR DESCRIPTION
**Pull request by agazso**
This PR adds the mobile version of the app.

Notes:
- There were also style changes, for example the icons are removed from most buttons. There may be some leftovers because the Figma version evolved as well during the work on this PR. If there are some minor differences they will be done in a separate PR, because this PR already touched too many files.
- All screens are supposed to be responsive (with breakpoint at 1024) and serviceable.
- The portfolio view got a major layout change and also the view link is updated. There were heavy refactorings to reduce duplication, but still there are some
- The charts got overhauled, but the breakdown chart needs one more iteration. It will be done as a separate PR
- There were effort made to unify the headers and also the general layout. Still the `Fullscreen` component uses a separate layout than the `ContentLayout`. This can be done as a separate PR.
- There were size issues with the calendar in the sidebar, because at 380px width the calendar (which is 360px wide) did not fit completely. The sidebar was increased to 400px and in Diete 06 the compact calendar is smaller. 
- On mobile screens less than 768px the calendar is displayed as a modal in small size. This is quite unexpected and it does not use the modal so it cannot be closed with clicking outside and also the modal background does not cover the whole app. (#977)
- The onboarding on the portfolio page is not optimized for mobile (#978)

Fixes #973 
Fixes #960 
Fixes #873 
Fixes #704 
Fixes #565 
Fixes #564 
Fixes #562

### CODE REVIEW

File: knip.ts [hunk 1]
```diff
@@ -7,7 +7,12 @@ const config: KnipConfig = {
 		'$env/*': ['.svelte-kit/ambient.d.ts'],
 		'$lib/*': ['src/lib/*'],
 	},
-	ignore: ['src/lib/typesdb.ts', 'playwright/index.ts', 'scripts/test-locales-examples.svelte'],
+	ignore: [
+		'src/lib/typesdb.ts',
+		'playwright/index.ts',
+		'scripts/test-locales-examples.svelte',
+		'src/lib/not-implemented.ts',
```
Comment (vojtechsimetka) [inline knip.ts]: I would probably just remove this

**Review by vojtechsimetka — APPROVED** [review]
Very nice! I found only one issue - when loading the header is there twice. I suggest to fix that and then merge. We will find other problems as we continue developing.

File: src/lib/components/fullscreen.svelte [hunk 2]
```diff
@@ -1,15 +1,24 @@
...
 	import type { Snippet } from 'svelte'
 	import CustomHeader from './custom-header.svelte'
+	import Header from './header.svelte'
+	import { authStore } from '$lib/stores/auth.svelte'
 	let {
 		children,
-		hasCloseButton = true,
-		beta = false,
-	}: { children: Snippet; hasCloseButton?: boolean; beta?: boolean } = $props()
+		hasCustomHeader = authStore.user ? false : true,
```
Comment (vojtechsimetka) [inline src/lib/components/fullscreen.svelte:8]: This is probably why there are two headers
