### PR TITLE
fix: localization initialization

### LINKED ISSUE #899: Localization initialization
The locale should be initialized in the main `+layout.svelte`, the logic could be the following:
- If you are logged in, use the language from the settings
- If not logged in use the language of the website (stored in localStorage)
- Else use the browser default locale

### PR DESCRIPTION
**Pull request by agazso**
Initialize the locale based on user/browser preference, described in #899 

Fixes #899

### CODE REVIEW

File: src/routes/+layout.svelte [hunk 1]
```diff
@@ -4,9 +4,40 @@
...
+	import { get } from 'svelte/store'
+	import { authStore } from '$lib/stores/auth.svelte'
+	import { browser } from '$app/environment'
+	import { defaultLocale, LOCALE_STORAGE_KEY } from '$lib/locales'
 
 	let { children } = $props()
 
+	$effect(() => {
+		const availableLocales = get(locales)
+		const localStorageLocale = localStorage.getItem(LOCALE_STORAGE_KEY)
```
Comment (vojtechsimetka) [inline src/routes/+layout.svelte]: This can fail on server side rendering IMHO.

File: src/routes/account/+page.svelte [hunk 2]
```diff
@@ -65,6 +66,8 @@
 			})
 			// FIXME: handle the case when the user is not logged in
 			if (authStore.user) authStore.user.user_metadata.prefer_language = newLocale
+
+			localStorage.setItem(LOCALE_STORAGE_KEY, newLocale)
```
Comment (vojtechsimetka) [inline src/routes/account/+page.svelte]:
```suggestion
			if (browser) {
						localStorage.setItem(LOCALE_STORAGE_KEY, newLocale)
			}
```

File: src/lib/components/beta-landing-page.svelte [hunk 3]
```diff
@@ -17,6 +18,11 @@
 	}
 
 	const { isMobile }: Props = $props()
+
+	function setLocale(language: 'en' | 'cs') {
+		localStorage.setItem(LOCALE_STORAGE_KEY, language)
```
Comment (vojtechsimetka) [inline src/lib/components/beta-landing-page.svelte]:
```suggestion
		if (browser) {
				localStorage.setItem(LOCALE_STORAGE_KEY, language)
		}
```
