### PR TITLE
fix: redirect from reset password link to reset password page

### LINKED ISSUE #307: Reset password link should bring to reset password page
Currently it just logs me in and brings me to the homepage
It should bring me here

https://www.figma.com/design/SfxcQrddo63TTqJOOMQURZ/Kalkul_04?node-id=6197-9142&t=wIgAB7c64JAES9x6-1

### PR DESCRIPTION
**Pull request by hlavkat**
resolved #307

### CODE REVIEW

File: src/lib/adapters/supabase/index.ts [hunk 1]
```diff
@@ -194,13 +194,19 @@ export default class Supabase implements Adapter {
...
 
 	async sendResetPasswordLink(email: string) {
-		const { error } = await supabase.auth.resetPasswordForEmail(email)
+		const redirectTo =
+			window.location.hostname === 'localhost'
+				? 'http://localhost:5173/reset-password'
+				: 'https://kalkul.app/reset-password'
+
+		const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo })
+
```
Comment (vojtechsimetka) [inline src/lib/adapters/supabase/index.ts]:
```suggestion
		const redirectTo =
			`${window.location.origin}/reset-password`

		const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo })

```

**Review by vojtechsimetka — APPROVED** [review]
