### PR TITLE
fix: cumulative interest

### LINKED ISSUE #840: Cumulative interest calculation is wrong
In the breakdown chart, the interest earned can decrease in time and even be negative. Most likely this is due to the withdrawals but clearly thje calculation is wrong.

Image

### PR DESCRIPTION
**Pull request by agazso**
This PR fixes the cumulative interest calculation. It also fixes another bug where the breakdown chart's tooltip also counted the hidden investments as part of the total but the chart was showing the correct number, so there was a discrepancy between the two.

Fixes #840

### CODE REVIEW

File: src/lib/components/graph-portfolio-breakdown.svelte [hunk 1]
```diff
@@ -66,8 +66,19 @@
...
+		for (let i = 0; i <= index; i++) {
+			const valueChange = i === 0 ? values[i] : values[i] - values[i - 1]
+			const periodDeposits = deposits[i] || 0
+			const periodWithdrawals = withdrawals[i] || 0
+			const periodFees = fees[i] || 0
+
+			// Interest earned this period = value change - deposits - withdrawals - fees
+			const periodInterest = valueChange - periodDeposits - periodWithdrawals - periodFees
+			cumulativeInterest += periodInterest
+		}
```
Comment (vojtechsimetka) [inline src/lib/components/graph-portfolio-breakdown.svelte]: Nice, I wonder if we should not have this extracted somewhere with proper tests.

**Review by vojtechsimetka — APPROVED** [review]

File: src/lib/components/graph-portfolio-breakdown.svelte (hunk 1 above)
Comment (agazso) [reply src/lib/components/graph-portfolio-breakdown.svelte]: I extracted the functions and added tests for it and it made me realize that the interest can go negative if the investment loses value. I opened an issue about this: #844

**Review by vojtechsimetka — APPROVED** [review]
