### PR TITLE
fix: update help modal with get started

### LINKED ISSUE #876: Update Help modal with access to Get started page
Image

https://www.figma.com/design/CH1QlTIGJk5xblFsNLi3Kn/Kalkul_05?node-id=8665-54902&t=0YuhZTg4X3h52VLE-1

### PR DESCRIPTION
**Pull request by agazso**
Fixes #876

This change required also significant changes in the `check-locales` script, so I added a test file to make sure that there is no regression in its behavior.

### CODE REVIEW

File: src/lib/components/ui/button.svelte [hunk 1]
```diff
@@ -102,6 +104,10 @@
 		justify-content: flex-start;
 	}
 
+	.flexGrow {
+		flex-grow: 1 !important;
```
Comment (vojtechsimetka) [inline src/lib/components/ui/button.svelte:108]: This does not look like best practice :). I am fine with merging if it needs to be merged like this but we should create and issue about it. Similarly the `leftAlign` could be replace with `align: 'left' | 'center' | 'right'`

File: src/lib/locales/cs.json [hunk 2]
```diff
@@ -358,9 +358,10 @@
 		},
 		"help": {
 			"title": "Nápověda",
-			"text": "Pokud potřebujete pomoct, máte dotazy, návrhy nebo zpětnou vazbu, doporučujeme nás kontaktovat prostřednictvím našeho Discord serveru. Alternativně nás můžete kontaktovat e-mailem na {email}.",
-			"joinTheConversation": "Připojte se ke Kalkulu na Discordu",
-			"discordInfo": "Na Discordu také sdílíme novinky, aktualizace produktu a oznámení, nenechte si to ujít!"
+			"text": "Pokud potřebujete pomoct, máte dotazy, návrhy nebo zpětnou vazbu, připojte se na náš Discord server pro nejrychlejší podporu, nebo nám napište e-mail na {email}.",
+			"joinTheConversation": "Připojte se na Discord",
+			"newToKalkulTip": "→ Nový v Kalkulu? Doporučujeme zkontrolovat náš rychlý průvodce. Najdete v něm vše potřebné pro začátek.",
```
Comment (vojtechsimetka) [inline src/lib/locales/cs.json:363]:
```suggestion
			"newToKalkulTip": "→ Jste v Kalkulu noví? Podívejte se na náš rychlý průvodce rychlý průvodce. Najdete v něm vše potřebné pro začátek.",
```

**Review by vojtechsimetka — APPROVED** [review]
