### PR TITLE
fix: delete account text

### LINKED ISSUE #511: Delete account is not implemented
We can either remove the button or display `Coming soon!`. Implementing at this point would be counterproductive because this will change once the payments are involved. This may be better suited for implementation for the Early Bird release.

### PR DESCRIPTION
**Pull request by agazso**
Fixes #511

### CODE REVIEW

File: src/routes/account/+page.svelte [hunk 1]
```diff
@@ -165,7 +165,11 @@
 							>{$_('changePassword')}</Button
 						>
 						<FlexItem />
-						<Button dimension="compact" variant="ghost" onclick={notImplemented}
+						<Button
+							dimension="compact"
+							variant="ghost"
+							onclick={(e: Event) =>
+								notImplemented(e, $_('Contact support to delete your account with all its data'))}
```
Comment (vojtechsimetka) [inline src/routes/account/+page.svelte:172]: Maybe we should say where. I'd suggest `support@kalkul.app`, wdyt??

**Review by vojtechsimetka — APPROVED** [review]

File: src/routes/account/+page.svelte (hunk 1 above)
Comment (agazso) [reply src/routes/account/+page.svelte:172]: I am waiting for the design of the feedback popup with this (#584) and to have the address setup first (#586). After that we can change the text.
