### PR TITLE
fix: ISIN updates

### LINKED ISSUE #711: ISIN — add explanations
- add an explanation about how the APY is calculated with ISIN import 
- add an explanation that the ISIN import results are filtered by currency

### LINKED ISSUE #712: ISIN — no results screen
we need a design when there are no results to show

### PR DESCRIPTION
**Pull request by agazso**
This PR adds small updates to the ISIN search modal and fixes localization issues.

Fixes #711 
Fixes #712

### CODE REVIEW

File: src/lib/components/import-investment.svelte [hunk 1]
```diff
@@ -223,36 +227,71 @@
...
+					>{$_('component.editInvestment.matchingProductExplanation')}</Typography
+				>
+			</Vertical>
+
+			<Vertical --vertical-gap="var(--quarter-padding">
+				<li class="header">
+					<Typography variant="small" bold>{$_('Name')}</Typography>
+					<Typography variant="small" bold>{$_('Type')}</Typography>
+					<Typography variant="small" bold>{$_('Symbol')}</Typography>
+					<Typography variant="small" bold>{$_('Exchange')}</Typography>
```
Comment (vojtechsimetka) [inline src/lib/components/import-investment.svelte]: Please extract this to the locales.

**Review by vojtechsimetka — APPROVED** [review]
