### PR TITLE
fix: investment card menu dropdown

### LINKED ISSUE #563: Menu button on investment card has wrong size/proportions
Image

Also I'm not sure that I like the showing only on hover, I would prefer to remove this and show the button all the time.

### PR DESCRIPTION
**Pull request by agazso**
Also fixes dropdown default behavior.

Fixes #563

### CODE REVIEW

File: src/lib/components/investment-card.svelte [hunk 1]
```diff
@@ -207,9 +207,9 @@
 		}
 	}
 	.dropdown {
-		opacity: 0;
-		transition: opacity 0.2s ease-in;
-		visibility: hidden;
+		opacity: 1;
+		transition: opacity 0.2s ease-out;
+		visibility: visible;
```
Comment (vojtechsimetka) [inline src/lib/components/investment-card.svelte:212]: do we need this at all? Seems unnecessary since there is no opacity change ever and it is always visible

**Review by vojtechsimetka — APPROVED** [review]
