### PR TITLE
fix: mobile goals layout

### LINKED ISSUE #1071: Deleting an investment gets stuck on the delete modal
After reloading the page the investment is deleted correctly.

Image

### LINKED ISSUE #1091: Empty investment/goal state
`No data` is shown at the place of the chart when there is no investments or goals are created.

Screenshot From 2025-11-06 15-16-51

_Originally posted by @agazso in https://github.com/snaha/kalkul/issues/1072#issuecomment-3497475330_

### LINKED ISSUE #1095: Add APY badge to goal card
Image

### LINKED ISSUE #1101: Update text and button in goals card
Image

In our goals demo, the design had an "Add investments"  button under the goal. As agreed we will not have this feature until Milestone 4 but I think that we should still have some call-to-action here to help advisors understand what's next. The button would simply switch to goals (same than the tab nav on top).

### LINKED ISSUE #1104: Fixed position for sidebar header and footer
The switch between 'Goals' and 'Investments should be in container with fixed position on top of the sidebar, with cards scrolling under it

Image

Same for the Add button but at the bottom of the sidebar

Image

This is the same on mobile

https://www.figma.com/design/8m9igCPQt7UAlCMfu4e05y/Kalkul_07?node-id=2022-26064&t=hUiMVBxqTlWCrZxT-1

### LINKED ISSUE #1105: Optimised investment card design
Image

The investment card layout has been slightly redesigned to match / harmonise with the goals card
- moved APY badge on the same line than investment name
- moved 'Add transaction' button to the bottom of the card
- adjusted padding and gap to 8pt (from 16pt) so it's more compact and the same than goals card

Figma link: https://www.figma.com/design/8m9igCPQt7UAlCMfu4e05y/Kalkul_07?node-id=159-8293&t=hUiMVBxqTlWCrZxT-1

### LINKED ISSUE #1106: Optimised goal card design
Image

- changed the button to simply switch to investments tab
- new text
-  added definitions for hover states etc. (similar to investment card details #1105 )

### PR DESCRIPTION
**Pull request by agazso**
This PR implements the Goals/Investments tabbed sidebar layout and also implements the mobile layout. The portfolio header is going to be done in a separate PR.

Notes:
- There is a new `PortfolioSidebar` component that contains the layout and logic for the sidebar on the portfolio page.
- The sidebar is now fixed according to #1104 and the scrolling size has a calculated value based on the fixed elements (see `--portfolio-sidebar-min-height`). There are slight differences from the design in the size, mostly due to the `Button` component calculation which includes a 1px border

Fixes #1095
Partially addresses #1099 (except for the portfolio header)
Fixes #1104
Fixes #1105 
Fixes #1106 
Fixes #1101
Fixes #1071 
Fixes #1091

### CODE REVIEW

File: src/lib/adapters/supabase/index.ts [hunk 1]
```diff
@@ -340,7 +340,12 @@ export default class Supabase implements Adapter {
 	}
 
 	async deleteInvestment(investment: Partial<Investment> & Pick<Investment, 'id'>) {
-		return this.deleteData('investment', investment, investmentStore)
+		// Delete the investment first
+		await this.deleteData('investment', investment, investmentStore)
+
+		// Clean up orphaned transactions from the store
+		// (they're cascade-deleted in the database, but we need to sync the local store)
+		transactionStore.data = transactionStore.data.filter((t) => t.investment_id !== investment.id)
```
Comment (vojtechsimetka) [inline src/lib/adapters/supabase/index.ts:348]: This is technically not needed, right? Because the transactions are not shown if the goal does not exist.

File: src/lib/components/goal-card.svelte [hunk 2]
```diff
@@ -183,60 +199,46 @@
...
-							<Typography variant="small"
-								>{$_('component.investmentCard.noTransactionsYetText')}</Typography
-							>
-						{/if}
-					</section>
-				{:else}
+			</Vertical>
+		{:else}
+			<!-- svelte-ignore a11y_click_events_have_key_events -->
+			<!-- svelte-ignore a11y_no_static_element_interactions -->
```
Comment (vojtechsimetka) [inline src/lib/components/goal-card.svelte]: We should add the keydown events and tabindex which will resolve these linter issues.

File: src/lib/components/ui/tab-bar/tab-content.svelte [hunk 3]
```diff
@@ -4,7 +4,7 @@
 
 	type Props = {
 		value: string | Snippet
-		children: Snippet
+		children?: Snippet
```
Comment (vojtechsimetka) [inline src/lib/components/ui/tab-bar/tab-content.svelte:7]: Is this change needed? Will we have a tab without any content?

File: src/lib/adapters/supabase/index.ts (hunk 1 above)
Comment (agazso) [reply src/lib/adapters/supabase/index.ts:348]: I was debugging the #1071 bug and I wanted to cover all possible cases. On the UI we don't display transactions without investments, but there are also places in the code where we work with transactions and it felt safer this way.

File: src/lib/components/ui/tab-bar/tab-content.svelte (hunk 3 above)
Comment (agazso) [reply src/lib/components/ui/tab-bar/tab-content.svelte:7]: Yes, this is the case currently, in the portfolio-sidebar we have a tab bar where the content scrolls under the tabs. The code is cleaner if the tab bar is only used to select which tab to show, but the content is displayed in a scrolling div, with the actual content shown is a function of the selected tab.
I can also imagine other situations (for example we could use a tab bar on the value chart for choosing between the value or the breakdown charts).

File: src/lib/locales/cs.json [hunk 4]
```diff
@@ -577,6 +574,12 @@
 		},
 		"youtubeIntroVideo": {
 			"title": "Úvodní video"
+		},
+		"sidebar": {
+			"noGoalsYetTitle": "Zatím žádné cíle",
+			"noGoalsYetDescription": "Definujte finanční cíle a cílové částky na vysoké úrovni. Cíle vám pomohou udržet zaměření na celkový obraz.",
+			"noInvestmentsYetTitle": "Zatím žádné investice",
+			"noInvestmentsYetDescription": "Přidejte konkrétní investiční produkty a transakce, které tvoří portfolio vašeho klienta. Tip: propojte transakce s cíli, abyste je mohli snadno porovnat s celkovým cílem."
```
Comment (vojtechsimetka) [inline src/lib/locales/cs.json]:
```suggestion
			"noGoalsYetTitle": "Zatím žádné cíle",
			"noGoalsYetDescription": "Definujte hlavní finanční cíle a cílové částky. Cíle vám pomáhají soustředit se na celkový plán.",
			"noInvestmentsYetTitle": "Zatím žádné investice",
			"noInvestmentsYetDescription": "Přidejte konkrétní investiční produkty a transakce, které tvoří portfolio vašeho klienta. Tip: propojte transakce s cíli a snadno porovnávejte postup vůči celkovému plánu."
}
```

File: src/lib/locales/cs.json [hunk 5]
```diff
@@ -517,7 +513,8 @@
 			"duplicateGoal": "Duplikovat cíl",
 			"deleteGoal": "Smazat cíl",
 			"deleteGoalWarning": "Tento cíl bude trvale smazán. Nelze vrátit zpět.",
-			"deleteGoalWarningTitle": "Smazat cíl?"
+			"deleteGoalWarningTitle": "Smazat cíl?",
+			"explainInvestmentsText": "Nastavili jste velký obraz s tímto cílem. Nyní přejděte na kartu Investice a přidejte konkrétní produkty a transakce, které to umožní."
```
Comment (vojtechsimetka) [inline src/lib/locales/cs.json]:
```suggestion
			"deleteGoalWarningTitle": "Smazat cíl?",
			"explainInvestmentsText": "S cílem jste si nastavili rámec plánu. Nyní přejděte na kartu Investice a přidejte konkrétní produkty a transakce, které vám pomohou ho uskutečnit."
```

**Review by vojtechsimetka — APPROVED** [review]
