### PR TITLE
fix: add client page- added error state

### LINKED ISSUE #401: Any error when creating a client is silently ignored
When I try to create new client and client with the next sequencial PK already exists, the app stays on the page but all the input fields reset.

### PR DESCRIPTION
**Pull request by hlavkat**
resolved #401

### CODE REVIEW

File: src/lib/components/edit-client.svelte [hunk 1]
```diff
@@ -39,16 +41,20 @@
 		if (!birthDate) {
 			return
```
Comment (vojtechsimetka) [inline src/lib/components/edit-client.svelte:44]: We should also set the error here.

File: src/lib/components/edit-client.svelte [hunk 2]
```diff
@@ -39,16 +41,20 @@
...
+		try {
+			const client: ClientNoId = {
+				name,
+				birth_date: birthDate.toDateString(),
+			}
+			await adapter.addClient(client)
+			name = ''
+			birthDate = undefined
+			imageURI = undefined
+			error = undefined
```
Comment (vojtechsimetka) [inline src/lib/components/edit-client.svelte]: This should be at the start of the function

**Review by vojtechsimetka — CHANGES_REQUESTED** [review]
The error should always be set to `undefined` first.

File: src/lib/components/edit-client.svelte (hunk 1 above)
Comment (vojtechsimetka) [reply src/lib/components/edit-client.svelte:44]: @hlavkat please also set `error` here

File: src/lib/locales/en.json [hunk 3]
```diff
@@ -3,6 +3,7 @@
 	"name": "Name",
 	"birthDate": "Birthdate",
 	"birthDateError": "Birthdate cannot be in the future.",
+	"birthDateUndefined": "Set your birth date",
```
Comment (vojtechsimetka) [inline src/lib/locales/en.json]:
```suggestion
	"birthDateUndefined": "Please set valid birthdate",
```

File: src/lib/locales/cs.json [hunk 4]
```diff
@@ -3,6 +3,7 @@
 	"name": "Jméno",
 	"birthDate": "Datum narození",
 	"birthDateError": "Datum narození nemůže být v budoucnosti.",
+	"birthDateUndefined": "Nastav své datum narození",
```
Comment (vojtechsimetka) [inline src/lib/locales/cs.json]:
```suggestion
	"birthDateUndefined": "Nastav správné datum narození",
```

**Review by vojtechsimetka — APPROVED** [review]
