### PR TITLE
fix: implementation search function - filter by name

### LINKED ISSUE #312: Search is not working
Screenshot 2025-01-08 at 9 35 13

### PR DESCRIPTION
**Pull request by hlavkat**
resolved #312

### CODE REVIEW

File: src/routes/(app)/+page.svelte [hunk 1]
```diff
@@ -26,6 +26,8 @@
 
 	let showConfirmModal = $state(false)
 	let clientToBeDeleted: number | undefined = $state()
+	let searchQuery = $state('')
+	let filteredClient = $derived(searchByName())
```
Comment (vojtechsimetka) [inline src/routes/(app)/+page.svelte]:
```suggestion
	let filteredClient = $derived(searchByName(searchQuery))
```

File: src/routes/(app)/+page.svelte [hunk 2]
```diff
@@ -43,6 +45,15 @@
 			showConfirmModal = false
 		}
 	}
+	function searchByName() {
```
Comment (vojtechsimetka) [inline src/routes/(app)/+page.svelte]:
```suggestion
	function searchByName(searchQuery: string) {
```

**Review by vojtechsimetka — COMMENTED** [review]
It is generally an anti-pattern to have state variables in functions. These should be passed in as arguments.

**Review by vojtechsimetka — APPROVED** [review]
